# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
    -   id: autopep8
        args: ["-i", "--select=E1,W291"]

-   repo: https://github.com/Unifield/prepyflakes.git
    rev: f20c7cc83f8
    hooks:
    - id: prepyflakes

- repo: https://github.com/Unifield/pre-sql-injection.git
  rev: 9a187cc1b5d60
  hooks:
  - id: pre-sql-injection

- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v6.0.0
  hooks:
    - id: check-merge-conflict
      args: ["--assume-in-merge"]
